language: cpp

sudo: required
dist: trusty

os:
  - linux

#to avoid an infinite loop, before_deploy creates a tag which will re run travis
branches:
  except:
  - /^linux-b.*$/
  - /^macosx-b.*$/

before_install:
  - sudo apt-get update -qq
  # install the gnu debugger for later use in reading the core file
  - sudo apt-get -y install gdb

#Install lib that cannot be install using travis addon
install:
  # This is to apt-get the packages needed to build omni
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && ./bootstrap.py 3
      && ./bootstrap.py 11
      ;
    fi
 # What is the current file size max for core files?
 # It is usually 0, which means no core file will be dumped if there is a crash 
  - ulimit -c

before_script: 
# Set the core file limit to unlimited so a core file is generated upon crash
 - ulimit -c unlimited -S

#After executing the script, make sure to be in the repo root folder, otherwise the deploy script will fail
script:
  - echo "#define BUILD $TRAVIS_BUILD_NUMBER" > build_number.h
# TEMP ORIGINAL optimized - make desktop OPT=release CC=$CC CXX=$CXX
  - make desktop CC=$CC CXX=$CXX
 # more details for core dump https://github.com/springmeyer/travis-coredump
 # Run the program to prompt a crash
 # Note: we capture the return code of the program here and add
 # `|| true` to ensure that travis continues past the crash
  - ./bin/debug/omni.desktop.test || RESULT=$?
  - if [[ ${RESULT} == 0 ]]; then echo "\\o/ our test worked without problems"; else echo "ruhroh test returned an errorcode of $RESULT"; fi;
 # If the program returned an error code, now we check for a
 # core file in the current working directory and dump the backtrace out
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
 # now we should present travis with the original
 # error code so the run cleanly stops
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;

before_deploy:
  #
  # add a tag
  #
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER
      ;
    fi
  - git tag $GIT_TAG 
  - git push -q https://$GH_TOKEN@github.com/seung-lab/omni.play --tags

deploy:
- provider: releases
  api_key: $GH_TOKEN
  file: 
  # TEMP FOR Debug
  - ./bin/debug/omni.desktop
  skip_cleanup: true
  on:
      repo: seung-lab/omni.play
      branch: 
       - master
       - staging
      tags: false
      condition: ${TRAVIS_OS_NAME} = linux
