language: cpp

sudo: required
dist: trusty

os:
  - linux

#to avoid an infinite loop, before_deploy creates a tag which will re run travis
branches:
  except:
  - /^linux-b.*$/
  - /^macosx-b.*$/

before_install:
  - sudo apt-get update -qq

#Install lib that cannot be install using travis addon
install:
  # This is to apt-get the packages needed to build omni
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && ./bootstrap.py 3
      && ./bootstrap.py 11
      ;
    fi

#After executing the script, make sure to be in the repo root folder, otherwise the deploy script will fail
script:
  - echo "#define BUILD $TRAVIS_BUILD_NUMBER" > build_number.h
  - make desktop CC=$CC CXX=$CXX
before_deploy:
  #
  # add a tag
  #
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER
      ;
    fi
  - git tag $GIT_TAG 
  - git push -q https://$GH_TOKEN@github.com/seung-lab/omni.play --tags

deploy:
- provider: releases
  api_key: $GH_TOKEN
  file: 
  - ./bin/debug/omni.desktop
  skip_cleanup: true
  on:
      repo: seung-lab/omni.play
      branch: 
       - master
       - travis
      tags: false
      condition: ${TRAVIS_OS_NAME} = linux
