#############################################################################
# Makefile for building: bin/omni.server
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Oct 3 10:38:33 2011
# Project:  omni.server.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile omni.server.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g $(DEFINES)
CXXFLAGS      = -pipe -Werror=return-type -DZI_USE_OPENMP -fopenmp -gstabs+ -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_SPIRIT_THREADSAFE -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_FILESYSTEM_VERSION=3 -DBOOST_FILESYSTEM_NO_DEPRECATED -g $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -Isrc -Iinclude -Ilib -Itests -Iexternal/libs/Boost/include -Iexternal/libs/thrift/include/thrift
LINK          = g++
LFLAGS        = -DZI_USE_OPENMP -fopenmp -gstabs+
LIBS          = $(SUBLIBS)   external/libs/Boost/lib/libboost_filesystem.a external/libs/Boost/lib/libboost_iostreams.a external/libs/Boost/lib/libboost_system.a external/libs/Boost/lib/libboost_thread.a external/libs/thrift/lib/libthrift.a 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/thrift/server.cpp \
		src/thrift/server_constants.cpp \
		src/thrift/server_types.cpp 
OBJECTS       = build/main.o \
		build/server.o \
		build/server_constants.o \
		build/server_types.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		omni.server.pro
QMAKE_TARGET  = omni.server
DESTDIR       = bin/
TARGET        = bin/omni.server

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: omni.server.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf
	$(QMAKE) -unix -o Makefile omni.server.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile omni.server.pro

dist: 
	@$(CHK_DIR_EXISTS) build/omni.server1.0.0 || $(MKDIR) build/omni.server1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/omni.server1.0.0/ && (cd `dirname build/omni.server1.0.0` && $(TAR) omni.server1.0.0.tar omni.server1.0.0 && $(COMPRESS) omni.server1.0.0.tar) && $(MOVE) `dirname build/omni.server1.0.0`/omni.server1.0.0.tar.gz . && $(DEL_FILE) -r build/omni.server1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


src/thrift/server.cpp: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

src/thrift/server.h: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

src/thrift/server_constants.cpp: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

src/thrift/server_constants.h: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

src/thrift/server_types.cpp: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

src/thrift/server_types.h: if/server.thrift
	external/libs/thrift/bin/thrift -r --out src/thrift --gen cpp if/server.thrift

compiler_clean: 

####### Compile

build/main.o: src/main.cpp src/serverHandler.hpp \
		src/thrift/server.h \
		src/thrift/server_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/server.o: src/thrift/server.cpp src/thrift/server.h \
		src/thrift/server_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/server.o src/thrift/server.cpp

build/server_constants.o: src/thrift/server_constants.cpp src/thrift/server_constants.h \
		src/thrift/server_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/server_constants.o src/thrift/server_constants.cpp

build/server_types.o: src/thrift/server_types.cpp src/thrift/server_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/server_types.o src/thrift/server_types.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

