/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "filesystem_constants.h"

namespace om { namespace server {

const filesystemConstants g_filesystem_constants;

filesystemConstants::filesystemConstants() {
}

}} // namespace

