/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef old_server_H
#define old_server_H

#include <TProcessor.h>
#include "server_types.h"

namespace om { namespace server {

class old_serverIf {
 public:
  virtual ~old_serverIf() {}
  virtual void get_volume_bounds(bbox& _return) = 0;
  virtual void get_chan_tile(tile& _return, const vector3d& point, const int32_t mipLevel) = 0;
  virtual void get_seg_tile(tile& _return, const vector3d& point, const int32_t mipLevel, const int32_t segId) = 0;
  virtual int32_t get_seg_id(const vector3d& point) = 0;
  virtual void get_seg_bbox(bbox& _return, const int32_t segId) = 0;
  virtual void get_seg_ids(std::vector<int32_t> & _return, const vector3d& point, const double radius) = 0;
  virtual double compare_results(const std::vector<result> & old_results, const result& new_result) = 0;
};

class old_serverNull : virtual public old_serverIf {
 public:
  virtual ~old_serverNull() {}
  void get_volume_bounds(bbox& /* _return */) {
    return;
  }
  void get_chan_tile(tile& /* _return */, const vector3d& /* point */, const int32_t /* mipLevel */) {
    return;
  }
  void get_seg_tile(tile& /* _return */, const vector3d& /* point */, const int32_t /* mipLevel */, const int32_t /* segId */) {
    return;
  }
  int32_t get_seg_id(const vector3d& /* point */) {
    int32_t _return = 0;
    return _return;
  }
  void get_seg_bbox(bbox& /* _return */, const int32_t /* segId */) {
    return;
  }
  void get_seg_ids(std::vector<int32_t> & /* _return */, const vector3d& /* point */, const double /* radius */) {
    return;
  }
  double compare_results(const std::vector<result> & /* old_results */, const result& /* new_result */) {
    double _return = (double)0;
    return _return;
  }
};


class old_server_get_volume_bounds_args {
 public:

  old_server_get_volume_bounds_args() {
  }

  virtual ~old_server_get_volume_bounds_args() throw() {}


  bool operator == (const old_server_get_volume_bounds_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const old_server_get_volume_bounds_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_volume_bounds_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_volume_bounds_pargs {
 public:


  virtual ~old_server_get_volume_bounds_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_volume_bounds_result__isset {
  _old_server_get_volume_bounds_result__isset() : success(false) {}
  bool success;
} _old_server_get_volume_bounds_result__isset;

class old_server_get_volume_bounds_result {
 public:

  old_server_get_volume_bounds_result() {
  }

  virtual ~old_server_get_volume_bounds_result() throw() {}

  bbox success;

  _old_server_get_volume_bounds_result__isset __isset;

  void __set_success(const bbox& val) {
    success = val;
  }

  bool operator == (const old_server_get_volume_bounds_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_volume_bounds_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_volume_bounds_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_volume_bounds_presult__isset {
  _old_server_get_volume_bounds_presult__isset() : success(false) {}
  bool success;
} _old_server_get_volume_bounds_presult__isset;

class old_server_get_volume_bounds_presult {
 public:


  virtual ~old_server_get_volume_bounds_presult() throw() {}

  bbox* success;

  _old_server_get_volume_bounds_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_get_chan_tile_args__isset {
  _old_server_get_chan_tile_args__isset() : point(false), mipLevel(false) {}
  bool point;
  bool mipLevel;
} _old_server_get_chan_tile_args__isset;

class old_server_get_chan_tile_args {
 public:

  old_server_get_chan_tile_args() : mipLevel(0) {
  }

  virtual ~old_server_get_chan_tile_args() throw() {}

  vector3d point;
  int32_t mipLevel;

  _old_server_get_chan_tile_args__isset __isset;

  void __set_point(const vector3d& val) {
    point = val;
  }

  void __set_mipLevel(const int32_t val) {
    mipLevel = val;
  }

  bool operator == (const old_server_get_chan_tile_args & rhs) const
  {
    if (!(point == rhs.point))
      return false;
    if (!(mipLevel == rhs.mipLevel))
      return false;
    return true;
  }
  bool operator != (const old_server_get_chan_tile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_chan_tile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_chan_tile_pargs {
 public:


  virtual ~old_server_get_chan_tile_pargs() throw() {}

  const vector3d* point;
  const int32_t* mipLevel;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_chan_tile_result__isset {
  _old_server_get_chan_tile_result__isset() : success(false) {}
  bool success;
} _old_server_get_chan_tile_result__isset;

class old_server_get_chan_tile_result {
 public:

  old_server_get_chan_tile_result() {
  }

  virtual ~old_server_get_chan_tile_result() throw() {}

  tile success;

  _old_server_get_chan_tile_result__isset __isset;

  void __set_success(const tile& val) {
    success = val;
  }

  bool operator == (const old_server_get_chan_tile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_chan_tile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_chan_tile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_chan_tile_presult__isset {
  _old_server_get_chan_tile_presult__isset() : success(false) {}
  bool success;
} _old_server_get_chan_tile_presult__isset;

class old_server_get_chan_tile_presult {
 public:


  virtual ~old_server_get_chan_tile_presult() throw() {}

  tile* success;

  _old_server_get_chan_tile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_get_seg_tile_args__isset {
  _old_server_get_seg_tile_args__isset() : point(false), mipLevel(false), segId(false) {}
  bool point;
  bool mipLevel;
  bool segId;
} _old_server_get_seg_tile_args__isset;

class old_server_get_seg_tile_args {
 public:

  old_server_get_seg_tile_args() : mipLevel(0), segId(0) {
  }

  virtual ~old_server_get_seg_tile_args() throw() {}

  vector3d point;
  int32_t mipLevel;
  int32_t segId;

  _old_server_get_seg_tile_args__isset __isset;

  void __set_point(const vector3d& val) {
    point = val;
  }

  void __set_mipLevel(const int32_t val) {
    mipLevel = val;
  }

  void __set_segId(const int32_t val) {
    segId = val;
  }

  bool operator == (const old_server_get_seg_tile_args & rhs) const
  {
    if (!(point == rhs.point))
      return false;
    if (!(mipLevel == rhs.mipLevel))
      return false;
    if (!(segId == rhs.segId))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_tile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_tile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_seg_tile_pargs {
 public:


  virtual ~old_server_get_seg_tile_pargs() throw() {}

  const vector3d* point;
  const int32_t* mipLevel;
  const int32_t* segId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_tile_result__isset {
  _old_server_get_seg_tile_result__isset() : success(false) {}
  bool success;
} _old_server_get_seg_tile_result__isset;

class old_server_get_seg_tile_result {
 public:

  old_server_get_seg_tile_result() {
  }

  virtual ~old_server_get_seg_tile_result() throw() {}

  tile success;

  _old_server_get_seg_tile_result__isset __isset;

  void __set_success(const tile& val) {
    success = val;
  }

  bool operator == (const old_server_get_seg_tile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_tile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_tile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_tile_presult__isset {
  _old_server_get_seg_tile_presult__isset() : success(false) {}
  bool success;
} _old_server_get_seg_tile_presult__isset;

class old_server_get_seg_tile_presult {
 public:


  virtual ~old_server_get_seg_tile_presult() throw() {}

  tile* success;

  _old_server_get_seg_tile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_get_seg_id_args__isset {
  _old_server_get_seg_id_args__isset() : point(false) {}
  bool point;
} _old_server_get_seg_id_args__isset;

class old_server_get_seg_id_args {
 public:

  old_server_get_seg_id_args() {
  }

  virtual ~old_server_get_seg_id_args() throw() {}

  vector3d point;

  _old_server_get_seg_id_args__isset __isset;

  void __set_point(const vector3d& val) {
    point = val;
  }

  bool operator == (const old_server_get_seg_id_args & rhs) const
  {
    if (!(point == rhs.point))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_id_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_id_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_seg_id_pargs {
 public:


  virtual ~old_server_get_seg_id_pargs() throw() {}

  const vector3d* point;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_id_result__isset {
  _old_server_get_seg_id_result__isset() : success(false) {}
  bool success;
} _old_server_get_seg_id_result__isset;

class old_server_get_seg_id_result {
 public:

  old_server_get_seg_id_result() : success(0) {
  }

  virtual ~old_server_get_seg_id_result() throw() {}

  int32_t success;

  _old_server_get_seg_id_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const old_server_get_seg_id_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_id_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_id_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_id_presult__isset {
  _old_server_get_seg_id_presult__isset() : success(false) {}
  bool success;
} _old_server_get_seg_id_presult__isset;

class old_server_get_seg_id_presult {
 public:


  virtual ~old_server_get_seg_id_presult() throw() {}

  int32_t* success;

  _old_server_get_seg_id_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_get_seg_bbox_args__isset {
  _old_server_get_seg_bbox_args__isset() : segId(false) {}
  bool segId;
} _old_server_get_seg_bbox_args__isset;

class old_server_get_seg_bbox_args {
 public:

  old_server_get_seg_bbox_args() : segId(0) {
  }

  virtual ~old_server_get_seg_bbox_args() throw() {}

  int32_t segId;

  _old_server_get_seg_bbox_args__isset __isset;

  void __set_segId(const int32_t val) {
    segId = val;
  }

  bool operator == (const old_server_get_seg_bbox_args & rhs) const
  {
    if (!(segId == rhs.segId))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_bbox_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_bbox_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_seg_bbox_pargs {
 public:


  virtual ~old_server_get_seg_bbox_pargs() throw() {}

  const int32_t* segId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_bbox_result__isset {
  _old_server_get_seg_bbox_result__isset() : success(false) {}
  bool success;
} _old_server_get_seg_bbox_result__isset;

class old_server_get_seg_bbox_result {
 public:

  old_server_get_seg_bbox_result() {
  }

  virtual ~old_server_get_seg_bbox_result() throw() {}

  bbox success;

  _old_server_get_seg_bbox_result__isset __isset;

  void __set_success(const bbox& val) {
    success = val;
  }

  bool operator == (const old_server_get_seg_bbox_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_bbox_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_bbox_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_bbox_presult__isset {
  _old_server_get_seg_bbox_presult__isset() : success(false) {}
  bool success;
} _old_server_get_seg_bbox_presult__isset;

class old_server_get_seg_bbox_presult {
 public:


  virtual ~old_server_get_seg_bbox_presult() throw() {}

  bbox* success;

  _old_server_get_seg_bbox_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_get_seg_ids_args__isset {
  _old_server_get_seg_ids_args__isset() : point(false), radius(false) {}
  bool point;
  bool radius;
} _old_server_get_seg_ids_args__isset;

class old_server_get_seg_ids_args {
 public:

  old_server_get_seg_ids_args() : radius(0) {
  }

  virtual ~old_server_get_seg_ids_args() throw() {}

  vector3d point;
  double radius;

  _old_server_get_seg_ids_args__isset __isset;

  void __set_point(const vector3d& val) {
    point = val;
  }

  void __set_radius(const double val) {
    radius = val;
  }

  bool operator == (const old_server_get_seg_ids_args & rhs) const
  {
    if (!(point == rhs.point))
      return false;
    if (!(radius == rhs.radius))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_ids_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_ids_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_get_seg_ids_pargs {
 public:


  virtual ~old_server_get_seg_ids_pargs() throw() {}

  const vector3d* point;
  const double* radius;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_ids_result__isset {
  _old_server_get_seg_ids_result__isset() : success(false) {}
  bool success;
} _old_server_get_seg_ids_result__isset;

class old_server_get_seg_ids_result {
 public:

  old_server_get_seg_ids_result() {
  }

  virtual ~old_server_get_seg_ids_result() throw() {}

  std::vector<int32_t>  success;

  _old_server_get_seg_ids_result__isset __isset;

  void __set_success(const std::vector<int32_t> & val) {
    success = val;
  }

  bool operator == (const old_server_get_seg_ids_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_get_seg_ids_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_get_seg_ids_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_get_seg_ids_presult__isset {
  _old_server_get_seg_ids_presult__isset() : success(false) {}
  bool success;
} _old_server_get_seg_ids_presult__isset;

class old_server_get_seg_ids_presult {
 public:


  virtual ~old_server_get_seg_ids_presult() throw() {}

  std::vector<int32_t> * success;

  _old_server_get_seg_ids_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _old_server_compare_results_args__isset {
  _old_server_compare_results_args__isset() : old_results(false), new_result(false) {}
  bool old_results;
  bool new_result;
} _old_server_compare_results_args__isset;

class old_server_compare_results_args {
 public:

  old_server_compare_results_args() {
  }

  virtual ~old_server_compare_results_args() throw() {}

  std::vector<result>  old_results;
  result new_result;

  _old_server_compare_results_args__isset __isset;

  void __set_old_results(const std::vector<result> & val) {
    old_results = val;
  }

  void __set_new_result(const result& val) {
    new_result = val;
  }

  bool operator == (const old_server_compare_results_args & rhs) const
  {
    if (!(old_results == rhs.old_results))
      return false;
    if (!(new_result == rhs.new_result))
      return false;
    return true;
  }
  bool operator != (const old_server_compare_results_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_compare_results_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class old_server_compare_results_pargs {
 public:


  virtual ~old_server_compare_results_pargs() throw() {}

  const std::vector<result> * old_results;
  const result* new_result;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_compare_results_result__isset {
  _old_server_compare_results_result__isset() : success(false) {}
  bool success;
} _old_server_compare_results_result__isset;

class old_server_compare_results_result {
 public:

  old_server_compare_results_result() : success(0) {
  }

  virtual ~old_server_compare_results_result() throw() {}

  double success;

  _old_server_compare_results_result__isset __isset;

  void __set_success(const double val) {
    success = val;
  }

  bool operator == (const old_server_compare_results_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const old_server_compare_results_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const old_server_compare_results_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _old_server_compare_results_presult__isset {
  _old_server_compare_results_presult__isset() : success(false) {}
  bool success;
} _old_server_compare_results_presult__isset;

class old_server_compare_results_presult {
 public:


  virtual ~old_server_compare_results_presult() throw() {}

  double* success;

  _old_server_compare_results_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class old_serverClient : virtual public old_serverIf {
 public:
  old_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  old_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_volume_bounds(bbox& _return);
  void send_get_volume_bounds();
  void recv_get_volume_bounds(bbox& _return);
  void get_chan_tile(tile& _return, const vector3d& point, const int32_t mipLevel);
  void send_get_chan_tile(const vector3d& point, const int32_t mipLevel);
  void recv_get_chan_tile(tile& _return);
  void get_seg_tile(tile& _return, const vector3d& point, const int32_t mipLevel, const int32_t segId);
  void send_get_seg_tile(const vector3d& point, const int32_t mipLevel, const int32_t segId);
  void recv_get_seg_tile(tile& _return);
  int32_t get_seg_id(const vector3d& point);
  void send_get_seg_id(const vector3d& point);
  int32_t recv_get_seg_id();
  void get_seg_bbox(bbox& _return, const int32_t segId);
  void send_get_seg_bbox(const int32_t segId);
  void recv_get_seg_bbox(bbox& _return);
  void get_seg_ids(std::vector<int32_t> & _return, const vector3d& point, const double radius);
  void send_get_seg_ids(const vector3d& point, const double radius);
  void recv_get_seg_ids(std::vector<int32_t> & _return);
  double compare_results(const std::vector<result> & old_results, const result& new_result);
  void send_compare_results(const std::vector<result> & old_results, const result& new_result);
  double recv_compare_results();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class old_serverProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<old_serverIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (old_serverProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_get_volume_bounds(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_chan_tile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_seg_tile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_seg_id(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_seg_bbox(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_seg_ids(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_compare_results(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  old_serverProcessor(boost::shared_ptr<old_serverIf> iface) :
    iface_(iface) {
    processMap_["get_volume_bounds"] = &old_serverProcessor::process_get_volume_bounds;
    processMap_["get_chan_tile"] = &old_serverProcessor::process_get_chan_tile;
    processMap_["get_seg_tile"] = &old_serverProcessor::process_get_seg_tile;
    processMap_["get_seg_id"] = &old_serverProcessor::process_get_seg_id;
    processMap_["get_seg_bbox"] = &old_serverProcessor::process_get_seg_bbox;
    processMap_["get_seg_ids"] = &old_serverProcessor::process_get_seg_ids;
    processMap_["compare_results"] = &old_serverProcessor::process_compare_results;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~old_serverProcessor() {}
};

class old_serverMultiface : virtual public old_serverIf {
 public:
  old_serverMultiface(std::vector<boost::shared_ptr<old_serverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~old_serverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<old_serverIf> > ifaces_;
  old_serverMultiface() {}
  void add(boost::shared_ptr<old_serverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get_volume_bounds(bbox& _return) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_volume_bounds(_return);
        return;
      } else {
        ifaces_[i]->get_volume_bounds(_return);
      }
    }
  }

  void get_chan_tile(tile& _return, const vector3d& point, const int32_t mipLevel) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_chan_tile(_return, point, mipLevel);
        return;
      } else {
        ifaces_[i]->get_chan_tile(_return, point, mipLevel);
      }
    }
  }

  void get_seg_tile(tile& _return, const vector3d& point, const int32_t mipLevel, const int32_t segId) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_seg_tile(_return, point, mipLevel, segId);
        return;
      } else {
        ifaces_[i]->get_seg_tile(_return, point, mipLevel, segId);
      }
    }
  }

  int32_t get_seg_id(const vector3d& point) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->get_seg_id(point);
      } else {
        ifaces_[i]->get_seg_id(point);
      }
    }
  }

  void get_seg_bbox(bbox& _return, const int32_t segId) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_seg_bbox(_return, segId);
        return;
      } else {
        ifaces_[i]->get_seg_bbox(_return, segId);
      }
    }
  }

  void get_seg_ids(std::vector<int32_t> & _return, const vector3d& point, const double radius) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_seg_ids(_return, point, radius);
        return;
      } else {
        ifaces_[i]->get_seg_ids(_return, point, radius);
      }
    }
  }

  double compare_results(const std::vector<result> & old_results, const result& new_result) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->compare_results(old_results, new_result);
      } else {
        ifaces_[i]->compare_results(old_results, new_result);
      }
    }
  }

};

}} // namespace

#endif
