/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "server_constants.h"

namespace om { namespace common {

const serverConstants g_server_constants;

serverConstants::serverConstants() {
}

}} // namespace

