#With thanks to: http://stackoverflow.com/questions/2481269/how-to-make-simple-c-makefile

CXX=g++
RM=/bin/rm -f
INCPATH=-Igtest-1.6.0/include -I../../omni.common/lib/include -I../external/libs/Boost/include -I../external/zi_lib\
	-I../../omni.common/external/libs/thrift/include/thrift/ -I../../omni.common/include/yaml-cpp/include\
	-I../../omni.common/include/ -I../src -I../include/libb64/include -I../external/libs/libpng/include
CPPFLAGS=-g $(shell root-config --cflags) $(INCPATH)
LDFLAGS=-g $(shell root-config --ldflags)
LDLIBS=$(shell root-config --libs)\
	../../omni.common/lib/bin/libomni.common.a\
	../external/libs/Boost/lib/libboost_filesystem.a\
	../external/libs/Boost/lib/libboost_iostreams.a\
	../external/libs/Boost/lib/libboost_system.a\
	../external/libs/Boost/lib/libboost_thread.a\
	../external/libs/Boost/lib/libboost_regex.a\
	../external/libs/thrift/lib/libthrift.a\
	../external/libs/libjpeg/lib/libturbojpeg.a\
	../external/libs/libpng/lib/libpng.a\
	../external/libs/zlib/lib/libz.a\
	gtest1.6.0/make/gtest_main.a

SRCS=$(wildcard src/*.cpp) $(wildcard ../src/handler/*.cpp)
OBJS=$(subst .cpp,.o,$(SRCS))

all: test

test: $(OBJS)
	g++ $(LDFLAGS) -o test $(OBJS) $(LDLIBS)

depend: .depend

.depend: $(SRCS)
	rm -f ./.depend
	$(CXX) $(CPPFLAGS) -MM $^>>./.depend;

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) *~ .dependtool

include .depend