// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include "../../storage_server.hpp"
#include "storage_manager.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>
#include <zi/hash.hpp>
#include <zi/system.hpp>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace bint;

class storage_managerHandler : virtual public storage_managerIf {
private:
    static size_t map_size = 10*1024*1024;

    storage_server<std::string,server_id> servers_;
    H hasher_;


public:
    storage_managerHandler()
	:servers_("manager_map",map_size),
	 hasher_()
    {
	// Your initialization goes here
    }

    void get_server(server_id& _return, const std::string& key) {
	// Your implementation goes here
	printf("get_server\n");
    }

    bool register_server(const server_id& id) {
	// Your implementation goes here
	printf("register_server\n");
    }

};

int main(int argc, char **argv) {
    int port = 9090;
    shared_ptr<storage_managerHandler> handler(new storage_managerHandler());
    shared_ptr<TProcessor> processor(new storage_managerProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);

    std::cout << zi::system::get_hostname() << ":" << port << std::endl;

    server.serve();


    return 0;
}

